services:
  - type: web
    name: parcred-dashboard
    env: python
    buildCommand: pip install -r requirements.txt && python -m playwright install chromium
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: GOOGLE_CREDS
        sync: false
      - key: BANKSOFT_USER
        sync: false
      - key: BANKSOFT_PASS
        sync: false
